- hosts: all
  become: true
  tasks:
  
   - debug: 
      msg: "total RAM : {{ ansible_memory_mb.real.total }}"
   - debug: 
      msg: "total free RAM : {{ ansible_memory_mb.real.free }}"
   - debug:
      msg: "OS family :{{ ansible_distribution }}"
   - debug:
      msg: "OS version : {{ ansible_distribution_major_version }}"
   - ec2_metadata_facts:
   - debug:
      msg: "Instance type : {{ ansible_ec2_instance_type }}"
   - debug:
      msg: "AMI id : {{ ansible_ec2_ami_id }}"
  
